# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(556, 394)
        MainWindow.setStyleSheet("background-color: rgba(88, 88, 88, 88);\n"
"border-top-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 0), stop:0.52 rgba(0, 0, 0, 0), stop:0.565 rgba(82, 121, 76, 33), stop:0.65 rgba(159, 235, 148, 64), stop:0.721925 rgba(255, 238, 150, 129), stop:0.77 rgba(255, 128, 128, 204), stop:0.89 rgba(191, 128, 255, 64), stop:1 rgba(0, 0, 0, 0));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.infopicker = QtWidgets.QGroupBox(self.centralwidget)
        self.infopicker.setStyleSheet("background-color: rgb(97, 97, 97);\n"
"    border: 2px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 1ex; /* leave space at the top for the title */")
        self.infopicker.setTitle("")
        self.infopicker.setObjectName("infopicker")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.infopicker)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.infopicker)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pathFile = QtWidgets.QLineEdit(self.infopicker)
        self.pathFile.setReadOnly(True)
        self.pathFile.setObjectName("pathFile")
        self.horizontalLayout.addWidget(self.pathFile)
        self.browse = QtWidgets.QPushButton(self.infopicker)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browse.setFont(font)
        self.browse.setObjectName("browse")
        self.horizontalLayout.addWidget(self.browse)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.infopicker)
        self.label_2.setMinimumSize(QtCore.QSize(135, 62))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.startRow = QtWidgets.QLineEdit(self.infopicker)
        self.startRow.setObjectName("startRow")
        self.horizontalLayout_2.addWidget(self.startRow)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lableEndRow = QtWidgets.QLabel(self.infopicker)
        self.lableEndRow.setMinimumSize(QtCore.QSize(135, 62))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lableEndRow.setFont(font)
        self.lableEndRow.setObjectName("lableEndRow")
        self.horizontalLayout_3.addWidget(self.lableEndRow)
        self.endRow = QtWidgets.QLineEdit(self.infopicker)
        self.endRow.setObjectName("endRow")
        self.horizontalLayout_3.addWidget(self.endRow)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelCountry = QtWidgets.QLabel(self.infopicker)
        self.labelCountry.setMinimumSize(QtCore.QSize(135, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelCountry.setFont(font)
        self.labelCountry.setObjectName("labelCountry")
        self.horizontalLayout_4.addWidget(self.labelCountry)
        self.country = QtWidgets.QLineEdit(self.infopicker)
        self.country.setObjectName("country")
        self.horizontalLayout_4.addWidget(self.country)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelworkCity = QtWidgets.QLabel(self.infopicker)
        self.labelworkCity.setMinimumSize(QtCore.QSize(135, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelworkCity.setFont(font)
        self.labelworkCity.setObjectName("labelworkCity")
        self.horizontalLayout_5.addWidget(self.labelworkCity)
        self.workCity = QtWidgets.QLineEdit(self.infopicker)
        self.workCity.setObjectName("workCity")
        self.horizontalLayout_5.addWidget(self.workCity)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.infopicker, 0, QtCore.Qt.AlignVCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setMinimumSize(QtCore.QSize(98, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancel.setFont(font)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_6.addWidget(self.cancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.horizontalLayout_6.addWidget(self.submit)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.cancel.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Ticket excel file picker"))
        self.browse.setText(_translate("MainWindow", "Browse"))
        self.label_2.setText(_translate("MainWindow", "Start Row"))
        self.lableEndRow.setText(_translate("MainWindow", "End Row"))
        self.labelCountry.setText(_translate("MainWindow", "Work Country"))
        self.labelworkCity.setText(_translate("MainWindow", "Work City"))
        self.cancel.setText(_translate("MainWindow", "Cancel"))
        self.submit.setText(_translate("MainWindow", "Submit"))
